
function [AFC_cumsum, AFC_ideal] = ...
      psycho_calcAFCCumsum(AFC_hist)
  
  [AFC_mode, num_hist_bins] = ...
      size(AFC_hist);
  
  AFC_cumsum = ...
      1 - cumsum( AFC_hist, 2 );
  
  AFC_ideal = ...
      0.5 + 0.5 * AFC_cumsum(1,:);
  ideal_denom = ...
      ( (AFC_mode - 1) + ((AFC_mode - 1)==0) )
  for i_AFC = 2 : AFC_mode
    AFC_ideal =  AFC_ideal + ...
	AFC_cumsum(i_AFC, :) / ...
	ideal_denom;
  end
